version: '3.8'

services:
  programierprojekt:
    image: programierprojekt:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/code/app
