name: build and deploy - beta

on:
  push:
    branches:
      - 'beta'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev
          docker build -t europe-west4-docker.pkg.dev/${GOOGLE_PROJECT}/progback-beta/app:latest --build-arg D_DB_HOST=${{ secrets.DB_HOST }} --build-arg D_DB_PORT=${{ secrets.DB_PORT }} --build-arg D_DB_PW=${{ secrets.DB_PW }} --build-arg D_DB_SCHEMA=${{ secrets.DB_SCHEMA }} .
          docker push europe-west4-docker.pkg.dev/${GOOGLE_PROJECT}/progback-beta/app:latest
          gcloud run services update beta --image europe-west4-docker.pkg.dev/${GOOGLE_PROJECT}/progback-beta/app:latest --region europe-west4
