name: build and deploy

on: ['push']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install google cloud cli
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev
          docker build -t europe-west4-docker.pkg.dev/${GOOGLE_PROJECT}/progbackcomp .
          docker push europe-west4-docker.pkg.dev/${GOOGLE_PROJECT}/progbackcomp
